# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-13 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Service',
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServicedCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ServicedCar',
                'verbose_name': 'Обслуживаемый автомобиль ',
                'verbose_name_plural': 'Обслуживаемые автомобили',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='Тип услуги', max_length=500, unique=True, verbose_name='Тип услуг')),
                ('serviced_cars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar')),
            ],
            options={
                'db_table': 'ServiceType',
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
    ]
