# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20170615_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedcar',
            name='car_type',
            field=models.CharField(default='Авто', max_length=500, verbose_name='Тип автомобиля'),
        ),
    ]
