# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_servicedcar_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedcar',
            name='car_type',
            field=models.CharField(max_length=500, verbose_name='Тип автомобиля'),
        ),
    ]
