# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170615_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedcar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
    ]
