# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicedcar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviced_cars',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar', verbose_name='Тип автомобиля'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.OneToOneField(default=11, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='servicedcar',
            name='car_type',
            field=models.CharField(default='Тип авто', max_length=500, verbose_name='Тип автомобиля'),
        ),
    ]
