# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170615_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='serviced_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar', verbose_name='Тип автомобиля'),
        ),
    ]
