# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170615_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
