# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20170616_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviced_cars',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
