# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 04:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20170616_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Наименование услуга', max_length=500, verbose_name='Название')),
                ('service_cost', models.CharField(default='Договрная', max_length=100, verbose_name='Стоимость')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType', verbose_name='Тип услуги')),
                ('serviced_cars', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar', verbose_name='Тип автомобиля')),
            ],
            options={
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуга',
                'db_table': 'Service',
            },
        ),
    ]
