# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20170616_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Наименование услуга', max_length=500, verbose_name='Название')),
                ('service_cost', models.CharField(default='Договрная', max_length=100, verbose_name='Стоимость')),
                ('service_description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'db_table': 'Service',
                'verbose_name_plural': 'Услуги',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='Тип услуги', max_length=500, unique=True, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('serviced_cars', models.ManyToManyField(blank=True, null=True, to='services.ServicedCar', verbose_name='Обслуживаемые авто')),
            ],
            options={
                'db_table': 'ServiceType',
                'verbose_name_plural': 'Типы услуг',
                'verbose_name': 'Тип услуги',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServiceType', verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='service',
            name='serviced_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar', verbose_name='Тип автомобиля'),
        ),
    ]
