# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20170616_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(default='Тип авто', max_length=500, verbose_name='Тип автомобиля')),
                ('means', models.CharField(blank=True, default='ТАНТАЛ', max_length=50, null=True, verbose_name='Средство')),
                ('service', models.CharField(default='Наименование услуга', max_length=500, verbose_name='Название')),
                ('cost', models.CharField(default='Договрная', max_length=100, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name_plural': 'Антикоррозионные обработки',
                'db_table': 'Anticor',
                'verbose_name': 'Антикоррозионная обработка',
            },
        ),
    ]
