# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-17 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20170617_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedcar',
            name='car_type',
            field=models.CharField(default='Тип авто', max_length=500, unique=True, verbose_name='Тип автомобиля'),
        ),
    ]
