# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0036_auto_20170618_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='materials_used',
        ),
        migrations.AddField(
            model_name='service',
            name='materials_used',
            field=models.ManyToManyField(blank=True, null=True, to='services.MaterialUsed', verbose_name='Используемые материалы'),
        ),
    ]
