# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0038_auto_20170618_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='material_used',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviced_cars',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='serviced_cars',
        ),
        migrations.DeleteModel(
            name='MaterialUsed',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServicedCar',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
