# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0040_auto_20170618_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='img',
            field=models.CharField(default='07', max_length=10, verbose_name='Номер изображения'),
        ),
    ]
