# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_remove_servicetype_shortcut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serviced_cars',
        ),
        migrations.AddField(
            model_name='service',
            name='serviced_cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.ServicedCar', verbose_name='Тип автомобиля'),
        ),
    ]
