# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0051_auto_20170621_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение для раздела'),
        ),
    ]
