# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20170623_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='from_date_time',
            field=models.DateTimeField(verbose_name='Время отправления'),
        ),
    ]
