# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-30 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20170623_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='smsSendingSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.UUIDField(help_text='app_id доступен после регистрации на сайте sms.ru в разделе "Программистам"', verbose_name='app_id')),
                ('recipient_phone', models.CharField(help_text='Номер телефона на который будет отправляться смс', max_length=25, verbose_name='Номер телефона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'verbose_name_plural': 'Настройки отправки смс',
                'verbose_name': 'Настройка отправки смс',
                'db_table': 'smsSendingSetting',
            },
        ),
    ]
