# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_smssendingsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='smsSendingSetting',
        ),
        migrations.AlterField(
            model_name='message',
            name='from_message',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Сообщение'),
        ),
    ]
