# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-23 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=50, verbose_name='Имя отправителя')),
                ('from_email', models.EmailField(max_length=500, verbose_name='Email отправителя')),
                ('from_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон отправителя')),
                ('from_message', models.CharField(blank=True, max_length=500, null=True, verbose_name='Сообщение')),
                ('from_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправления')),
            ],
            options={
                'db_table': 'Messages',
                'verbose_name_plural': 'Сообщения',
                'verbose_name': 'Сообщениe',
            },
        ),
    ]
